
SERVER_HOST = "0.0.0.0" #bind address
SERVER_PORT = 4444 #default MTGNP port
MAX_CLIENTS = 2 #maximum 2 players
MAX_PDU_SIZE = 65535 #max pdu size
LENGTH_PREFIX_BYTES = 4 #big-endian unsigned int length prefix

#If VERBOSE is True, it means the program should show extra information about what it's doing.
#reference this as constants.VERBOSE
VERBOSE = False 

#getter setter method to ensure we get the updated value of verbose
def set_verbose(value: bool) -> None:
    global VERBOSE
    VERBOSE = bool(value)

def is_verbose() -> bool:
    return VERBOSE

#TIMING RULES
DEFAULT_TIME_LIMIT_MS = 60000 #default time limit
HEARTBEAT_INTERVAL_S = 30 #recommended client ping interval based on specs
HEARTBEAT_TIMEOUT_S = 10 #recommended pong wait before disconnect

#GAME SETUP RULES
STARTING_LIFE = 20
STARTING_HAND_SIZE = 7
MIN_DECK_SIZE = 1
MAX_DECK_SIZE = 50
MAX_HAND_SIZE_BEFORE_DISCARD = 7

#TURN PHASE ORDER (what comes after logic)
PHASE_ORDER = [
    "UNTAP",
    "UPKEEP",
    "DRAW",
    "PRECOMBAT_MAIN",
    "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS",
    "ASSIGN_DAMAGE_ORDER", #only if attacker has 2+ blocker
    "FIRST_STRIKE_DAMAGE", #optional, only if first/double strike is present
    "COMBAT_DAMAGE",
    "POSTCOMBAT_MAIN",
    "END_STEP",
    "CLEANUP"
]

#phases when both players can act
#untap and cleanup become automatic
PRIORITY_PHASES = {
    "UPKEEP",
    "DRAW",
    "PRECOMBAT_MAIN",
    "BEGIN_COMBAT",
    "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS",
    "ASSIGN_DAMAGE_ORDER",
    "FIRST_STRIKE_DAMAGE",
    "COMBAT_DAMAGE",
    "END_OF_COMBAT",
    "POSTCOMBAT_MAIN",
    "END_STEP",
}

#GAME LIFECYCLE STATES
LOBBY = "LOBBY"
GAME_SETUP = "GAME_SETUP"
MULLIGAN = "MULLIGAN"
IN_GAME = "IN_GAME"
GAME_OVER = "GAME_OVER"

#ERROR CODES
ERROR_INVALID_JSON = "INVALID_JSON"
ERROR_ILLEGAL_DECK = "ILLEGAL_DECK"
ERROR_UNKNOWN_TYPE = "UNKNOWN_TYPE"
ERROR_STALE_ACTION = "STALE_ACTION"
ERROR_NOT_YOUR_PRIORITY = "NOT_YOUR_PRIORITY"
ERROR_ILLEGAL_ACTION = "ILLEGAL_ACTION"
ERROR_ILLEGAL_TARGET = "ILLEGAL_TARGET"
ERROR_TRIGGER_ORDER_INVALID = "TRIGGER_ORDER_INVALID"
ERROR_TRIGGER_CHOICE_INVALID = "TRIGGER_CHOICE_INVALID"
ERROR_INSUFFICIENT_MANA = "INSUFFICIENT_MANA"
ERROR_WRONG_PHASE = "WRONG_PHASE"
ERROR_DUPLICATE_ID = "DUPLICATE_ID"
ERROR_SERVER_FULL = "SERVER_FULL"

ALL_ERROR_CODES = {
    ERROR_INVALID_JSON, ERROR_ILLEGAL_DECK, ERROR_UNKNOWN_TYPE,
    ERROR_STALE_ACTION, ERROR_NOT_YOUR_PRIORITY, ERROR_ILLEGAL_ACTION,
    ERROR_ILLEGAL_TARGET, ERROR_TRIGGER_ORDER_INVALID,
    ERROR_TRIGGER_CHOICE_INVALID, ERROR_INSUFFICIENT_MANA,
    ERROR_WRONG_PHASE, ERROR_DUPLICATE_ID, ERROR_SERVER_FULL,
}

#GAMEOVER REASONS
REASON_LIFE_ZERO = "LIFE_ZERO"
REASON_DECK_EMPTY = "DECK_EMPTY"
REASON_CONCEDE = "CONCEDE"
REASON_DISCONNECT = "DISCONNECT"

#PDU TYPE STRINGS
PDU_TYPES = {
    "PLAYER_READY", "GAME_STATE_UPDATE", "MULLIGAN_CHOICE", "PHASE_TRANSITION",
    "PRIORITY_GRANT", "PRIORITY_PASS", "CAST_SPELL", "ACTIVATE_ABILITY",
    "STACK_PUSH", "TRIGGER_ORDER", "TRIGGER_ORDER_RESPONSE", "TRIGGER_CHOICE",
    "TRIGGER_CHOICE_RESPONSE", "STACK_RESOLVE", "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER", "COMBAT_DAMAGE_RESULT",
    "PLAY_LAND", "DISCARD", "CONCEDE", "GAME_OVER", "ERROR", "PING", "PONG",
}

#Client PDUs that need to echo a priority token
PRIORITY_ECHO_TYPES = {
    "CAST_SPELL", "ACTIVATE_ABILITY", "PRIORITY_PASS", "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER", "PLAY_LAND", "MULLIGAN_CHOICE",
    "DISCARD", "TRIGGER_ORDER_RESPONSE", "TRIGGER_CHOICE_RESPONSE",
}